1.In 2015, ___________, a new species of the genus Homo was discovered in the Dinaledi Chamber of the
Rising star cave system, Cradle of Humankind, South Africa

2.Which of the following is NOT a computer virus?
3. Which of the following is the largest glacier in India?
4.If the pH value of a substance is lower than 7, it would be considered as
5.In 1831, electricity became viable for use in technology when ________ created the electric dynamo.
6.Sound waves are _________ waves.
7.How many bones does a new born human baby have?
8.Which of the following coloured light has the lowest frequency?
9.The only non-metal which is liquid at room temperature is
10.Which of the following insecticides’ harmful effects came under
media attention when health issues in Kerala were publicized?
11.In 1981, ISRO launched India’s first geostationary satellite called
12.Where is White Desert is located?
13.Where did the Chipko movement begin?
14.What is most common treatment for bacterial infections in humans?
15.What is an archipelago?
16.Which among the following is popularly called Laughing gas
17.Mica is available abundantly in which state?
18.What is The Siberian ibex?
19.Which among the following happens in an oxidation reaction?
20.Which vitamin among the following is crucial for blood clotting?
21.Malgudi Days is based on the works of which Indian Writer?
22.What is the science or art of designing and accelerating projectiles so as to achieve a desired
performance called?
23.Find the similarity in the following:
Orange, Peach, Olive, Carmine
24.Which is the most abundant combustible natural gas?
25.What are Vivipara?
26.What is a Limerick?
27.Andromeda is a 
28.What is Oneirology, the study of?
29.What is an interstellar cloud of dust, hydrogen, helium and other ionized gases called?
30.The Victoria Falls are on the river 
31.Which one is not a network protocol?
(a) SSH
(b) HTML
(c) PPP
(d) POP
31.. National Air Quality Index is determined on the basis of concentration of _____pollutants
32.Who is considered to be the ‘father of modern genetics’?
33.Name the country whose currency is not called ‘Rupee’.
(a) Nepal
(b) Pakistan
(c) Sri Lanka
(d) Myanmar
34.Which one is anti-virus?
(a) CodeRed
(b) Melissa
(c) CryptoLocker
(d) Dr. Web
35.Western blot is the diagnostic test for
